### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Koc** [sebhoerl/Twig-netbeans#14]
I have file base_layout.html.twig, and plugin version 1.1. No any autocomplete or color-highlight

http://habrastorage.org/storage/ffa6f532/970afe5f/bfd1f2ff/cb36faa3.png

**Comment by Ziiweb** [comment]
Yes, the same for me.

**Comment by atma** [comment]
Highlighting is work for me but when I change almost one letter in the .twig file CPU usage going to 100% for ever.
NetBeans IDE 7.0 (Build 201104080000)
Java: 1.6.0_24
Plugin: stable v1.2

**Comment by sebhoerl** [comment]
Does it work with the new rewritten version?

**Comment by Koc** [comment]
where can I download compiled 1.2 version?

**Comment by atma** [comment]
Build from current source http://dl.dropbox.com/u/426176/NB/org-netbeans-modules-php-twig.nbm
But I still have CPU problems. Maybe it is my local issue.

**Comment by atma** [comment]
Nope. After deactivate -> uninstall -> stop nb -> clear nb cache -> start nb -> install -> restart nb  it is working like a charm

**Comment by Koc** [comment]
> blogsh uploaded a file to blogsh/Twig-netbeans about 20 hours ago
> "org-netbeans-modules-php-twig.nbm" is at blogsh/Twig-netbeans/downloads
> 
>    Twig for Netbeans 1.0 (Rewritten version)

Why 1.0? In changelog

> Version 1.2

It had confused me. But now it works, thank you.
