### ISSUE TITLE
Plugin breaks code collapse in html

### ISSUE THREAD

**Issue by Koc** [sebhoerl/Twig-netbeans#15]
1) subj. http://habrastorage.org/storage/3a409eb2/18e4b077/7dd34172/6f29f09d.png no more possibility collapse div.
2) it would cool if will possible collapse twig-structures - blocks, for, set-endset, etc

**Comment by sebhoerl** [comment]
It took some time, but I finally figured out how to enable code folds for html.
Twig folds coming soon

**Comment by Koc** [comment]
Thank you. But there is also code collapse in js

``` js
    function a()
    {

    }
```

**Comment by sebhoerl** [comment]
Today I added a new parser based on the lexer rewrite. I use it to create error messages and also code folds for Twig. 
I'm interested whether the parser works as expected? Maybe I forgot some block elements or some exceptions where block elements can also be standalone elements (block, set) and so on... :)

The Javascript issue seems to have the same reason like all other Javascript problems (syntax highlighting, code completion...). I'll put them together in one issue
