### ISSUE TITLE
Netbeans code templates

### ISSUE THREAD

**Issue by josefvn** [sebhoerl/Twig-netbeans#17]
It'll be extremely awesome if we could use code templates as defined under Tools > Options > Editor > Code Templates. :)

**Comment by thaberkern** [comment]
+1 from me

**Comment by beberlei** [comment]
Also if you could parse the symfony style of templates .html.twig .json.twig and such and then enable the parsing of the non twig content in that regard, like you can get highlighting for html, js and php in .html files depending on the context.

**Comment by dailytabs** [comment]
+1

Having to choose (code templates [plain text, no twig lang installed] & no syntax highlighting) or (no code templates & syntax highlighting) is not good.

Twig already shows up in the Code Templates tab's Language drop-down, the templates just never expand :/

**Comment by dailytabs** [comment]
Workaround:
Add them to the HTML language instead.

Only tested on *.html.twig files. They will work inside and outside of {%/{{ blocks.

**Comment by rcerrejon** [comment]
d-man97, in HTML language works for me, thanks.

**Comment by TiS** [comment]
d-man97, thanks, saved a lot of time for me.

**Comment by lintuxt** [comment]
@dailytabs you're da MVP! :+1:
