### ISSUE TITLE
Make it for NetBeans 7.1 too

### ISSUE THREAD

**Issue by Monomachus** [sebhoerl/Twig-netbeans#32]
Please make it available for for NetBeans 7.1 too

**Comment by sebhoerl** [comment]
I use the current version in Netbeans 7.1 beta without any problems. What exactly does not work?

**Comment by Koc** [comment]
+1, it works ok

**Comment by Monomachus** [comment]
Strangely enough I can't see it in the list of plugins for 7.1 and on the netbeans plugins site I see it is only for version 7.0

**Comment by sebhoerl** [comment]
The Twig plugin isn't listed in the list in Netbeans. Just download the nbm file from the Netbeans plugin repository or from here and install it manually. 
See https://github.com/blogsh/Twig-netbeans/blob/master/README

**Comment by Monomachus** [comment]
ok thanks.
