### ISSUE TITLE
Missing File Icon

### ISSUE THREAD

**Issue by monofone** [sebhoerl/Twig-netbeans#4]
Hi,
first thx a lot for this useful Plugin.
I´m missing an icon beside the Filename for twig files, I´ve created one on the fly.

http://blage.mine.nu/~srohweder/twig.png

Hope you like it and can use it, if you need another format, tell me.

Thx for yout great work

**Comment by sebhoerl** [comment]
Great! I'll include it in the next version.

**Comment by sebhoerl** [comment]
Added icon. Added &#39;New...&#39; template. Closed by d808b7d4d1a80acfbe63bd73bd5a7176c90cf9ef.
