### ISSUE TITLE
about the new validation

### ISSUE THREAD

**Issue by matteosister** [sebhoerl/Twig-netbeans#8]
first of all **good work**!

I found that there is a problem with validation.
This syntax do not validate and it should...

```
{% block title "Hello " ~ name %}
```

It's the shortcut for block with very small body, and not an "unclosed block".
I found this in Symfony2 standard edition. the file is:
src/Acme/DemoBundle/Resources/views/Secured/helloadmin.html.twig

**Comment by stof** [comment]
I confirm, the short syntax for blocks is not handled properly. `{% block title "Whatever" %}` should not search for an `{% endblock %}` tag

**Comment by sebhoerl** [comment]
Supports inline &#39;block&#39; and &#39;set&#39;. Closed by d82f9e9cb6accb16882d2417d0df69e64fa08614.
